import type { MetadataRoute } from 'next';

/**
 * Web app manifest.
 *
 * Generated by Next.js at `/manifest.webmanifest` rather than written as a
 * static file, so it stays typed and cannot drift from the app metadata.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Voyagr — AI travel deal hunter',
    short_name: 'Voyagr',
    description:
      'Voyagr keeps searching for a better complete trip after you close the tab, and tells you when it finds one.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait-primary',
    background_color: '#f7f9fb',
    theme_color: '#1c4f7c',
    categories: ['travel', 'productivity'],
    icons: [
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        // A maskable icon keeps the mark inside the safe zone when a launcher
        // applies its own shape.
        src: '/icons/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
